### PR TITLE
Feat/layout drafts

### PR DESCRIPTION
**Pull request by RafaelDavisH**
The first draft created with @Ola @Sophia @Ming(ming-yong) ideas shared on a google doc.

TODO:
- [ ] Links modal display.

Issue #2

### CODE REVIEW

**Comment by myg-main** [comment]
Hi @RafaelDavisH, I have a question to ask before merging your PR:
by the word "TODO", do you mean what you did in this PR?
Thanks a lot!

**Comment by RafaelDavisH** [comment]
> Hi @RafaelDavisH, I have a question to ask before merging your PR:
> by the word "TODO", do you mean what you did in this PR?
> Thanks a lot!

Hi @ming-yong, What I mean TODO: are the things I have pending to complete or add.

**Comment by zaynaib** [comment]
@RafaelDavisH  I did not get a notification when you tagged me. Try using @zaynaib instead. 🤷‍♀

**Comment by RafaelDavisH** [comment]
> zaynaib

Sorry about that @zaynaib. I think I missed your text on Discord when you shared your GitHub username. I'll add it right now.

**Pull request merged**
